package calculatrice;

import calculatrice.exeptions.MonException;

public class Operation {
    
    protected double calcul(double a,double b) throws MonException{
        return 0; 
    }
}
